site_name: Sinesp
site_author: Grupo 5
site_description: >-
  Documentação para o rojeto de avaliação da disciplina de requisitos de software 
 
# Repository
repo_url: https://github.com/Requisitos-de-Software/2024.1-Sinesp_Cidadao
repo_name: 2024.1-Sinesp_Cidadao


# Configuration
docs_dir: docs
theme: 
  name: material
  language: pt-BR
  favicon: assets/logo.png
  logo: ../assets/Logos/Logo_sinesp.png
  icon: 
   repo: fontawesome/brands/github
  font: 
    text: Roboto
  features:
  - navigation.instant
  - navigation.section
  - navigation.path
  - navigation.top
  - navigation.tabs
  - navigation.tabs.sticky

  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Mudar para o modo escuro
     
    - scheme: slate 
      toggle:
        icon: material/brightness-4
        name: Mudar para o modo claro

  extra_css: [stylesheets/extra.css]
  
nav: 
  - Início: index.md
  - Atas:
      - Ata 1: atas/Ata_Reuniao1_25_03_2024.md
      - Ata 2: atas/Ata_Reuniao2_31_03_2024.md
      - Ata 3: atas/Ata_Reuniao3__07_04_2024.md
      - Ata 4: atas/Ata_Reuniao4_14_04_2024.md
      - Ata 5: atas/Ata_Reuniao5_19_04_2024.md
  - Planejamento:
      - Lista de Aplicativos: Planejamento/Lista_de_aplicativos.md
      - Aplicativo Escolhido: Planejamento/App_selecionado.md
      - Cronograma: Planejamento/cronograma.md
      - Heatmap: Planejamento/heatmap.md
      - Rich Pictures: Planejamento/Rich_pictures.md
      - Ferramentas: Planejamento/ferramentas.md
  - Elicitação: 
      - Perfil de usuário: elicitacao/Perfil_de_usuario.md
      - Técnicas:
          - Questionario: elicitacao/tecnicas/questionario.md
          - Analise de Interface: elicitacao/tecnicas/AnaliseDaInterface.md
          - Analise de Documento: elicitacao/tecnicas/AnaliseDeDocumento.md
          - Analise de Protocolo: elicitacao/tecnicas/AnaliseDeProtocolo.md
          - Entrevista: elicitacao/tecnicas/Entrevista.md
          - Introspecção: elicitacao/tecnicas/Introspeccao.md
          - Storytelling: elicitacao/tecnicas/storytelling.md
      - Requisitos Elicitados: elicitacao/Requisitos_elicitados.md
      - Priorização: 
          - MOSCOW: elicitacao/priorizacao/Moscow.md
          - 100$: elicitacao/priorizacao/100$.md
          - FTF: elicitacao/priorizacao/FTF.md
          - Three Scales: elicitacao/priorizacao/three_scales.md

